name: Dev deploy

on:
  push:
    branches:
      - development

jobs:
  deploy:
    name: 🎉 Deploy Dev
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: 🔨 Build Project
        run: |
          corepack enable
          yarn set version 4.12.0           
          yarn install --no-immutable
          cp .env.example .env
          yarn build

      - name: 📂 Deploy to Server via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'susantimegah'
          server: '103.89.4.98'
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: 'dist/*'
          remote_path: '/home/susantimegah/public_html/smesta-dev.susantimegah.com/'
