name: Prod deploy

# Controls when the action will run.
on:
  push:
    branches:
      - production # Diubah menjadi branch production

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: 🔨 Build Project
        run: |
          corepack enable
          yarn set version 4.12.0           
          yarn
          yarn build

      - name: 📂 Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: 'dist/'
          REMOTE_HOST: 82.29.156.38
          REMOTE_USER: u106957989
          REMOTE_PORT: '65002'
          # Pastikan path target di bawah ini sesuai dengan folder domain customerportal Anda
          TARGET: domains/customerportal.susantimegah.com/public_html
          EXCLUDE: '/build/'
