name: Prod deploy

# Controls when the action will run.
on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: 🔨 Build Project
        run: |
          corepack enable
          yarn set version 4.12.0           
          yarn install --no-immutable
          sed -i 's/api-dev.susantimegah.com/api-sm-connect.susantimegah.com/g' .env
          sed -i 's/VITE_TURNSTILE_ENABLED=false/VITE_TURNSTILE_ENABLED=true/g' .env
          yarn build

      - name: 📂 Deploy to Server via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'susantimegah'
          server: '103.89.4.98' # 👈 Diubah dari 'host' menjadi 'server'
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # 👈 Diubah dari 'key' menjadi 'ssh_private_key'
          local_path: 'dist/*'
          remote_path: '/home/susantimegah/public_html/sm-connect.susantimegah.com/'
