name: Prod deploy

# Controls when the action will run.
on:
  push:
    branches:
      - production # Hanya jalan saat Anda push ke branch production

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: 🔨 Build Project
        run: |
          corepack enable
          yarn set version 4.12.0           
          yarn
          yarn build

      - name: 📂 Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: 'dist/' # folder hasil build
          REMOTE_HOST: 103.89.4.98 # IP VPS cPanel Anda
          REMOTE_USER: susantimegah # Username cPanel Anda yang baru
          REMOTE_PORT: '22' # Port SSH cPanel
          TARGET: /home/susantimegah/public_html/customerportal.susantimegah.com/ # Folder website Anda
          EXCLUDE: '/build/'
